In [1]:
import pandas as pd
import numpy as np

data=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/data_2020cafe/inheo_final.csv")

In [2]:
data.head()

   개방자치단체코드                    관리번호 자치구명  ...    호선  distance d_code
0   3000000  3000000-104-1990-09100  종로구  ...  03호선   0.26746      1
1   3000000  3000000-104-1990-09107  종로구  ...  03호선   0.29035      2
2   3000000  3000000-104-1990-09129  종로구  ...  01호선   0.33209      2
3   3000000  3000000-104-1990-09181  종로구  ...  06호선   0.23171      1
4   3000000  3000000-104-1990-09188  종로구  ...  06호선   0.05603      1

[5 rows x 32 columns]

In [3]:
feat_drop=['개방자치단체코드','관리번호','업소일련번호', '폐업구분','상권_코드','총층수','업소위치']
data=data.drop(feat_drop, axis=1)

In [4]:
data.head()

  자치구명         행정동명      년도       인허가일자  ...         SY    호선 distance d_code
0  종로구          사직동  1990.0  1990-09-03  ...  37.575788  03호선  0.26746      1
1  종로구          사직동  1990.0  1990-09-03  ...  37.575788  03호선  0.29035      2
2  종로구  종로1.2.3.4가동  1990.0  1990-08-22  ...  37.570222  01호선  0.33209      2
3  종로구        숭인제2동  1990.0  1990-12-22  ...  37.573213  06호선  0.23171      1
4  종로구        숭인제1동  1990.0  1990-07-13  ...  37.573213  06호선  0.05603      1

[5 rows x 25 columns]

In [5]:
data.shape

(33918, 25)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33918 entries, 0 to 33917
Data columns (total 25 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   자치구명        33918 non-null  object
 1   행정동명        33545 non-null  object
 2   년도          33598 non-null  float64
 3   인허가일자       33918 non-null  object
 4   폐업일자        33918 non-null  object
 5   영업상태코드      33918 non-null  int64
 6   영업상태명       33918 non-null  object
 7   사업장명        33650 non-null  object
 8   X           32997 non-null  float64
 9   Y           32997 non-null  float64
 10  시설총규모       33918 non-null  float64
 11  규모분기        33918 non-null  int64
 12  총층수1        7969 non-null   float64
 13  업소위치분기      33918 non-null  int64
 14  영업기간        33918 non-null  int64
 15  당월_매출_금액    15809 non-null  float64
 16  당월_매출_건수    15809 non-null  float64
 17  점포수         15809 non-null  float64
 18  cluster_id  32997 non-null  float64
 19  역이름         32997 non-null  object
 20  SX          32997 non-null  float64
 21  SY          32997 non-null  float64
 22  호선          32997 non-null  object
 23  distance    32997 non-null  float64
 24  d_code      33918 non-null  int64
dtypes: float64(12), int64(5), object(8)
memory usage: 6.5+ MB

In [7]:
indexn=data[data['년도']>=2019].index
data.drop(indexn,inplace=True)

#data['영업기간']=data['영업기간'].fillna(data.groupby("행정동명")['영업기간'].transform("median"), inplace=True)
data["총층수1"]=data["총층수1"].fillna(1)

In [8]:
feat_drop=['당월_매출_금액','당월_매출_건수','점포수']
data=data.drop(feat_drop, axis=1)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31539 entries, 0 to 33917
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   자치구명        31539 non-null  object
 1   행정동명        31166 non-null  object
 2   년도          31219 non-null  float64
 3   인허가일자       31539 non-null  object
 4   폐업일자        31539 non-null  object
 5   영업상태코드      31539 non-null  int64
 6   영업상태명       31539 non-null  object
 7   사업장명        31298 non-null  object
 8   X           30672 non-null  float64
 9   Y           30672 non-null  float64
 10  시설총규모       31539 non-null  float64
 11  규모분기        31539 non-null  int64
 12  총층수1        31539 non-null  float64
 13  업소위치분기      31539 non-null  int64
 14  영업기간        31539 non-null  int64
 15  cluster_id  30672 non-null  float64
 16  역이름         30672 non-null  object
 17  SX          30672 non-null  float64
 18  SY          30672 non-null  float64
 19  호선          30672 non-null  object
 20  distance    30672 non-null  float64
 21  d_code      31539 non-null  int64
dtypes: float64(9), int64(5), object(8)
memory usage: 5.5+ MB

In [10]:
#indexn=data[data['년도']<1990].index
#data.drop(indexn,inplace=True)

In [11]:
data.isnull().sum()

자치구명            0
행정동명          373
년도            320
인허가일자           0
폐업일자            0
영업상태코드          0
영업상태명           0
사업장명          241
X             867
Y             867
시설총규모           0
규모분기            0
총층수1            0
업소위치분기          0
영업기간            0
cluster_id    867
역이름           867
SX            867
SY            867
호선            867
distance      867
d_code          0
dtype: int64

In [12]:
'''
#-성공여부
r=[0,730,999999]#일단 2년을 성공기준
g=[0,1]
data['성공여부']=pd.cut(data['영업기간'],bins=r,labels=g)
data['성공여부']=data['성공여부'].fillna(0)#확인사살
#data=data.drop('영업기간',axis=1)
data['성공여부']
'''

"\n#-성공여부\nr=[0,730,999999]#일단 2년을 성공기준\ng=[0,1]\ndata['성공여부']=pd.cut(data['영업기간'],bins=r,labels=g)\ndata['성공여부']=data['성공여부'].fillna(0)#확인사살\n#data=data.drop('영업기간',axis=1)\ndata['성공여부']\n"

In [13]:
#-창업월
data["인허가일자"] = pd.to_datetime(data["인허가일자"])
data['창업월'] = data['인허가일자'].dt.month
data['창업월']

0         9
1         9
2         8
3        12
4         7
         ..
33818    12
33819    12
33820    12
33821     8
33917     2
Name: 창업월, Length: 31539, dtype: int64

In [14]:
#-폐업월
data["폐업일자"] = pd.to_datetime(data["폐업일자"])
data['폐업월'] = data['폐업일자'].dt.month
#data=data.drop('인허가일자',axis=1)
data['폐업월']

0         9
1         9
2         6
3         9
4         8
         ..
33818    12
33819     9
33820     1
33821    12
33917    12
Name: 폐업월, Length: 31539, dtype: int64

In [15]:
#gu mapping
gu_mapping={"강남구":1, "강동구":2, "강북구":3, '강서구':4,'관악구':5,'광진구':6,'구로구':7,'금천구':8,'노원구':9,'도봉구':10,'동대문':11,'동작구':12,'마포구':13,'서대문':14,'서초구':15,'성동구':16,'성북구':17,'송파구':18,'양천구':19,'영등포':20,'용산구':21,'은평구':22,'종로구':23,'중구':24,'중랑구':25}
data['구_1_25']=data['자치구명'].map(gu_mapping)

#data=data.drop('자치구명',axis=1)
data['구_1_25']

0        23
1        23
2        23
3        23
4        23
         ..
33818     2
33819     2
33820     2
33821     2
33917     2
Name: 구_1_25, Length: 31539, dtype: int64

In [16]:
import plotly.express as px
is_franchise=data['사업장명'].str.contains("이디야|스타벅스|투썸|달콤커피|커피베이|할리스|탐앤탐스|폴바셋|커피나무|파스쿠찌|파스쿠치|빽다방|빈스빈스|엔제리너스|엔젤리너스|커피명가|카페베네|커피스미스|드롭탑|커피마마|더착한커피|더카페|커피에반하다|매머드커피|주커피|토프레소|카페보니또|전광수커피|그라찌에|띠아모|커피빈|더벤티|스무디킹")
#사업장명이 없는 건 프랜차이즈 아닌걸로하자
is_super_franchise=data['사업장명'].str.contains("이디야|스타벅스|투썸")
data["프랜차이즈여부_02"]=0
is_franchise=is_franchise.fillna(0)
is_super_franchise=is_super_franchise.fillna(0)
is_franchise=is_franchise.astype(int)
is_super_franchise=is_super_franchise.astype(int)
for i in range(0,40766):
  try:
    data["프랜차이즈여부_02"][i]=is_franchise[i]+is_super_franchise[i]
  except KeyError:
    continue
data["프랜차이즈여부_02"]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

0        0
1        0
2        0
3        0
4        0
        ..
33818    0
33819    0
33820    0
33821    0
33917    0
Name: 프랜차이즈여부_02, Length: 31539, dtype: int64

In [17]:
#호선 추출하기
data['sub_1_9']=data['호선'].str[:2]
data['sub_1_9']

0        03
1        03
2        01
3        06
4        06
         ..
33818    05
33819    09
33820    08
33821    08
33917    09
Name: sub_1_9, Length: 31539, dtype: object

In [18]:
data.head()

  자치구명         행정동명      년도      인허가일자  ... 폐업월  구_1_25 프랜차이즈여부_02 sub_1_9
0  종로구          사직동  1990.0 1990-09-03  ...   9      23          0      03
1  종로구          사직동  1990.0 1990-09-03  ...   9      23          0      03
2  종로구  종로1.2.3.4가동  1990.0 1990-08-22  ...   6      23          0      01
3  종로구        숭인제2동  1990.0 1990-12-22  ...   9      23          0      06
4  종로구        숭인제1동  1990.0 1990-07-13  ...   8      23          0      06

[5 rows x 27 columns]

In [20]:
feat_drop=['규모분기','cluster_id','사업장명','자치구명','행정동명','폐업일자','인허가일자','영업상태명','SY','SX','총층수1','폐업월','d_code','호선','역이름']
data=data.drop(feat_drop, axis=1)

In [23]:
data=data.dropna(axis=0)

In [24]:
data.head()

       년도  영업상태코드           X          Y  ...  창업월  구_1_25  프랜차이즈여부_02  sub_1_9
0  1990.0       2  126.970654  37.576068  ...    9      23           0       03
1  1990.0       2  126.970422  37.576234  ...    9      23           0       03
2  1990.0       2  126.986778  37.570982  ...    8      23           0       01
3  1990.0       2  127.018736  37.574082  ...   12      23           0       06
4  1990.0       2  127.015994  37.573633  ...    7      23           0       06

[5 rows x 12 columns]

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30360 entries, 0 to 33820
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   년도          30360 non-null  float64
 1   영업상태코드      30360 non-null  int64
 2   X           30360 non-null  float64
 3   Y           30360 non-null  float64
 4   시설총규모       30360 non-null  float64
 5   업소위치분기      30360 non-null  int64
 6   영업기간        30360 non-null  int64
 7   distance    30360 non-null  float64
 8   창업월         30360 non-null  int64
 9   구_1_25      30360 non-null  int64
 10  프랜차이즈여부_02  30360 non-null  int64
 11  sub_1_9     30360 non-null  object
dtypes: float64(5), int64(6), object(1)
memory usage: 3.0+ MB

In [26]:
data.to_csv("/content/drive/My Drive/Colab Notebooks/data_2020cafe/inheo_forR.csv")